#ifndef MSG_DEFINITIONS_H
#define MSG_DEFINITIONS_H

#define MAX_NUM_CSS_SENSORS 32
#define MAX_EFF_CNT 36
#define RW_EFF_CNT 36
#define MAX_OE_RECORDS 10
#define MAX_OE_COEFF 20

#endif  // MSG_DEFINITIONS_H
